version: "3.8"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: TaskDatabase  # Set default database name, override with environment variable
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"  

# volumes:
#   postgres_data:
